INSERT INTO users VALUES (1, 'user', 'user','1');
INSERT INTO users VALUES (2, 'admin', 'admin','2');
INSERT INTO users VALUES (3, 'su', 'su','3');

INSERT INTO userlist VALUES (1,'Layla', 'Roberts');
INSERT INTO userlist VALUES (2,'Layla', 'Roberts');
INSERT INTO userlist VALUES (3,'Layla', 'Roberts');
INSERT INTO userlist VALUES (4,'Layla', 'Roberts');
INSERT INTO userlist VALUES (5,'Layla', 'Roberts');
INSERT INTO userlist VALUES (6,'Layla', 'Roberts');
INSERT INTO userlist VALUES (7,'Layla', 'Roberts');
INSERT INTO userlist VALUES (8,'Layla', 'Roberts');
INSERT INTO userlist VALUES (9,'Layla', 'Roberts');
INSERT INTO userlist VALUES (10,'Layla', 'Roberts');
INSERT INTO userlist VALUES (11,'Layla', 'Roberts');
INSERT INTO userlist VALUES (12,'Layla', 'Roberts');
INSERT INTO userlist VALUES (13,'Layla', 'Roberts');
INSERT INTO userlist VALUES (14,'Layla', 'Roberts');
INSERT INTO userlist VALUES (15,'Layla', 'Roberts');
INSERT INTO userlist VALUES (16,'Layla', 'Roberts');
INSERT INTO userlist VALUES (17,'Layla', 'Roberts');
INSERT INTO userlist VALUES (18,'Layla', 'Roberts');
INSERT INTO userlist VALUES (19,'Layla', 'Roberts');
INSERT INTO userlist VALUES (20,'Layla', 'Roberts');
INSERT INTO userlist VALUES (21,'Layla', 'Roberts');
INSERT INTO userlist VALUES (22,'Layla', 'Roberts');
INSERT INTO userlist VALUES (23,'Layla', 'Roberts');
INSERT INTO userlist VALUES (24,'Layla', 'Roberts');
INSERT INTO userlist VALUES (25,'Layla', 'Roberts');